export default {
  BLOCKCHAIN: "BLOCKCHAIN",
  TRANSACRION: "TRANSACTION",
  SYSTEM: "SYSTEM",
  NEWBLOCK: "NEWBLOCK",
  CONFLICT: "CONFLICT",
  RESOLVE_CONFLICT: "RESOLVE_CONFLICT",
  SYSTEM: "SYSTEM",
  REWORD: "REWORD",
  NEWBLOCK: "NEWBLOCK"
};
